### ISSUE TITLE
Canot find module "ts-node"

### ISSUE THREAD

**Issue by XuShunyi** [zce/zce-cli#60]
```
本地全局安装zce-cli，执行zce命令创建项目报错，截图如下：
```

![51596107874_ pic_hd](https://user-images.githubusercontent.com/15355987/88917386-41441980-d29a-11ea-841e-cdc00e1e8ae3.jpg)

**Comment by zce** [comment]
试试我全新的脚手架工具：https://github.com/zce/caz

**Comment by zce** [comment]
> ```
> 本地全局安装zce-cli，执行zce命令创建项目报错，截图如下：
> ```
> 
> ![51596107874_ pic_hd](https://user-images.githubusercontent.com/15355987/88917386-41441980-d29a-11ea-841e-cdc00e1e8ae3.jpg)

你的这个问题应该是因为你本地克隆了这个项目，并且 link 到了全局。
